const { ROLES } = require('./roles');

const PERMISSIONS = {
  // Super Admin Permissions
  COMPANIES_VIEW: 'companies.view',
  COMPANIES_CREATE: 'companies.create',
  COMPANIES_EDIT: 'companies.edit',
  COMPANIES_DELETE: 'companies.delete',

  SUBSCRIPTIONS_VIEW: 'subscriptions.view',
  SUBSCRIPTIONS_MANAGE: 'subscriptions.manage',

  SYSTEM_AUDIT_VIEW: 'system_audit.view',
  SYSTEM_SETTINGS_MANAGE: 'system_settings.manage',

  // Tenant / Company Admin Permissions
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_CREATE: 'branches.create',
  BRANCHES_EDIT: 'branches.edit',
  BRANCHES_DELETE: 'branches.delete',

  STAFF_VIEW: 'staff.view',
  STAFF_CREATE: 'staff.create',
  STAFF_EDIT: 'staff.edit',
  STAFF_DELETE: 'staff.delete',

  AGENTS_VIEW: 'agents.view',
  AGENTS_CREATE: 'agents.create',
  AGENTS_EDIT: 'agents.edit',
  AGENTS_DELETE: 'agents.delete',

  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',
  CUSTOMERS_DELETE: 'customers.delete',

  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_EDIT: 'products.edit',
  PRODUCTS_DELETE: 'products.delete',

  FINANCE_VIEW: 'finance.view',
  FINANCE_CREATE: 'finance.create',
  FINANCE_EDIT: 'finance.edit',
  FINANCE_DELETE: 'finance.delete',

  COLLECTIONS_VIEW: 'collections.view',
  COLLECTIONS_CREATE: 'collections.create',

  PAYMENTS_VIEW: 'payments.view',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_EDIT: 'payments.edit',

  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_UPLOAD: 'documents.upload',
  DOCUMENTS_DELETE: 'documents.delete',

  SETTINGS_VIEW: 'settings.view',
  SETTINGS_EDIT: 'settings.edit',

  AUDIT_VIEW: 'audit.view',
};

// Default role to permission mappings
const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.BRANCHES_VIEW, PERMISSIONS.BRANCHES_CREATE, PERMISSIONS.BRANCHES_EDIT, PERMISSIONS.BRANCHES_DELETE,
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_CREATE, PERMISSIONS.STAFF_EDIT, PERMISSIONS.STAFF_DELETE,
    PERMISSIONS.AGENTS_VIEW, PERMISSIONS.AGENTS_CREATE, PERMISSIONS.AGENTS_EDIT, PERMISSIONS.AGENTS_DELETE,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT, PERMISSIONS.CUSTOMERS_DELETE,
    PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_EDIT, PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_CREATE, PERMISSIONS.FINANCE_EDIT, PERMISSIONS.FINANCE_DELETE,
    PERMISSIONS.COLLECTIONS_VIEW, PERMISSIONS.COLLECTIONS_CREATE,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE, PERMISSIONS.PAYMENTS_EDIT,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_UPLOAD, PERMISSIONS.DOCUMENTS_DELETE,
    PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.AGENTS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.COLLECTIONS_VIEW, PERMISSIONS.COLLECTIONS_CREATE,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW, PERMISSIONS.DOCUMENTS_UPLOAD,
  ],
  [ROLES.AGENT]: [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.COLLECTIONS_VIEW, PERMISSIONS.COLLECTIONS_CREATE,
    PERMISSIONS.PAYMENTS_VIEW, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.COLLECTIONS_VIEW,
    PERMISSIONS.PAYMENTS_VIEW,
  ],
  [ROLES.CUSTOMER]: [
    // Customers can only view their own finance data through dedicated customer endpoints
  ],
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
};
